### ISSUE TITLE
Including the Java 8 Improvements

### ISSUE THREAD

**Issue by michaelrolf** [crowdcode-de/KissMDA#47]
It would be great to implement the Java 8 Time-API in KissMDA, so that all the classes of this API can be used, without modelling them, over and over again.

It would be also great implement default methodes into the generated interfaces, if an attribute has a default value.

**Comment by lofidewanto** [comment]
We need to add following:
- LocalDateTime -> Java LocalDateTime
- LocalDate -> Java LocalDate
- LocalTime -> Java LocalTime
- ZonedDateTime ->Java ZonedDateTime

**Comment by lofidewanto** [comment]
Done, app-examples/kissmda-app-test updated with some new properties with data types above.

**Comment by lofidewanto** [comment]
We should not introduce LocalDate, better to have an option to use it instead of Date.

**Comment by lofidewanto** [comment]
I added a mechanism to overwrite the data types:

- Add an application.properties on your classpath
- Put something like:

```
kissmda.datatypes.mapping.type.**Date**=java.time.LocalDate
kissmda.datatypes.mapping.type.date=java.time.LocalDate
kissmda.datatypes.mapping.type.DateTime=de.lofi.Test
```

**Comment by lofidewanto** [comment]
We can now add application.properties in src/main/resources/application.properties.
Within this file you can overwrite the datatypes something like:

`kissmda.datatypes.mapping.type.Date=java.time.LocalDate
kissmda.datatypes.mapping.type.date=java.time.LocalDate
kissmda.datatypes.mapping.type.DateTime=de.lofi.Test`

**Comment by lofidewanto** [comment]
Done
