### ISSUE TITLE
Java interfaces of the model are not generated

### ISSUE THREAD

**Issue by cbraun1980** [crowdcode-de/KissMDA#54]
We are genarating our models in parallel in a multi threaded maven build. Sometimes one of the modules which generates interfaces via kissMDA, finishes successful but the Java interfaces of the model are not generated.
The next module which needs these generated interfaces, fails because it can not find it. Whan analyzing the bug we find out that the interfaces are not generated by kissMDA. The target folder is just empty.

It happens infrequently. So we can not activate debug mode all the time because our log files will get too big.

**Comment by lofidewanto** [comment]
Difficult to find, because this is randomly, therefore without more information, I cannot trace it.
